### ISSUE TITLE
ModuleNotFoundError: No module named 'rich'

### ISSUE THREAD

**Issue by NarayanaSabari** [giovanni-iannaccone/ians#6]
Traceback (most recent call last):
  File "/home/kali/Desktop/hacking/ians/code/ians.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'Traceback (most recent call last):
  File "/home/kali/Desktop/hacking/ians/code/ians.py", line 1, in <module>
    from rich.console import Console
ModuleNotFoundError: No module named 'rich'

i have tried to modify code 
but i can find bug in this 
all required packages were installed

**Comment by NarayanaSabari** [comment]
write
pip install requirments.txt 
this will install all requirements modules
